api/urls.py
from django.urls import path

from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.authtoken import views as rf_views

from idealab import views as idealab_views
from projects import views as project_views
from announcements import views as announcement_views



urlpatterns = [
    
    # API gateway for Ideas
    path('ideas/', idealab_views.IdeaList.as_view()),
    path('ideas/<int:pk>/', idealab_views.IdeaDetail.as_view()),

    # API gateway for Authors
    path('authors/', idealab_views.AuthorList.as_view()),
    path('authors/<int:pk>/', idealab_views.AuthorDetail.as_view()),

    # API gateway for Projects
    path('projects/', project_views.ProjectList.as_view()),
    path('projects/<int:pk>/', project_views.ProjectDetail.as_view()),

    # API gateway for Projects
    path('contributors/', project_views.ContributorList.as_view()),
    path('contributors/<int:pk>/', project_views.ContributorDetail.as_view()),

    # API gateway for Announcements
    path('announcements/', announcement_views.AnnouncementList.as_view()),
    path('announcements/<int:pk>/', announcement_views.AnnouncementDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

# token authentication framework
urlpatterns += [
    path('api-token-auth/', rf_views.obtain_auth_token)
]

idealab/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = 'idealab'

urlpatterns = [
    path('', views.index, name='index'),
]

join/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'join'
urlpatterns = [
	path('', views.index, name='index'),
	path('activate/<uidb64>/<token>', views.activate, name='activate'),
]

mos/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


handler404 = 'api.views.page_not_found'
handler500 = 'api.views.error'
handler400 = 'api.views.page_not_found'

urlpatterns = [
	path('', TemplateView.as_view(template_name='home/index.html')),
    path('api/', include('api.urls')),
	path('idealab/', include('idealab.urls')),
	path('projects/', include('projects.urls')),
	path('join/', include('join.urls')),
	path('about/', TemplateView.as_view(template_name='about/index.html')),
    path('calendar/', TemplateView.as_view(template_name='calendar/index.html')),
    path('announcements/', include('announcements.urls')),
    path('admin/', admin.site.urls),
    path('discord/', RedirectView.as_view(url='https://discord.gg/xbBPqdqr6n')),
    path('github/', RedirectView.as_view(url='https://github.com/makeopensource')),
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
	path('', views.index, name='index')
]

web/views/about.py
import yaml
from .jinja_filters import to_date
from starlette.templating import Jinja2Templates


templates = Jinja2Templates(directory='templates')
filters = {'to_date': to_date}
templates.env.filters.update(filters)


async def about(request):
    elements = {
        'request': request, 
        'software': await get_yaml('data/about.yml', 'software'), 
        'admins': await get_yaml('data/about.yml', 'admins')
    }
    return templates.TemplateResponse('about.html', elements)


async def get_yaml(yaml_file, attr):
    with open(f'{yaml_file}', 'r') as file:
        return yaml.safe_load(file)[attr]

templates/about/index.html
{% extends "base/base_template.html" %}
  
{% block content %}
<div class="container" style="max-width: 600px;">
    <div class="row mb-3">
        <h1 class="mb-4">About</h1>
        <h5>We are University at Buffalo's Open-Source Club!</h5>
        <p class="text-secondary"> 
            Our club is dedicated to the development and deployment of 
            open-source software. All projects created under the club 
            will be available to view and modify given the restrictions 
            of each individual project's license.
        </p>
    </div>

    <div class="row mb-3">
        <h2>Software</h2>
        {% load static %}
        <div class="container p-2 mb-2 bg-light rounded">
            <a href="https://makeopensource.org">
                <img class="float-start m-2" style="max-height: 40px;" src="{% static 'assets/icons/icon.png' %}">
            </a>
            <a href="https://github.com/makeopensource">
                <img class="float-start m-2" style="max-height: 40px;" src="{% static 'assets/icons/github-logo.png' %}">
            </a>
            <a href="https://discord.com">
                <img class="float-start m-2" style="max-height: 40px;" src="{% static 'assets/icons/Discord-Logo-Black.png' %}">
            </a>
            <a href="https://drive.google.com/drive/folders/1GnSilJXrW8HiSsiGugIxQwXaOaFy1wT1?usp=sharing">
                <img class="float-start m-2" style="max-height: 40px;" src="{% static 'assets/icons/drive-logo.png' %}">
            </a>
            <a href="https://ubuffalo-my.sharepoint.com/:f:/g/personal/njbrown4_buffalo_edu/EjeA3pUstb1Hlmh6H2OS7poBdM2_90W4X4A00f4I2Ki90A?e=NEHxT9">
                <img class="float-start m-2" style="max-height: 40px;" src="{% static 'assets/icons/onedrive.png' %}">
            </a>
        </div>

        <ul>
        </ul>
    </div>

    <div class="row mb-3">
        <h2>Our Team</h2>
        <div class="mb-2">
            <img 
                class="bg-dark rounded-circle me-3" 
                style="width: 75px; height: 75px; float: left;" 
                src="{% static 'assets/staff/emilkovacev.jpg' %}" />
            <div>
                <b>Emil Kovacev</b>
                <p>
                    <span class="text-primary">President</span><br>
                    Computer Science BS
                </p>
            </div>
        </div>

        <div class="mb-2">
            <img 
                class="bg-dark rounded-circle me-3" 
                style="width: 75px; height: 75px; float: left;" 
                src="{% static 'assets/staff/nickbrown.jpg' %}" />
            <div>
                <b>Nick Brown</b>
                <p>
                    <span class="text-primary">Vice President</span><br>
                    Computer Science BA
                </p>
            </div>
        </div>


        <div class="mb-2">
             <img 
                class="bg-dark rounded-circle me-3" 
                style="width: 75px; height: 75px; float: left;" 
                src="{% static 'assets/staff/adamrussell.jpg' %}" 
                />
            <div>
                <b>Adam Russell</b>
                <p>
                    <span class="text-primary">Events Coordinator</span><br>
                    Computer Science BS
                </p>
            </div>
        </div>

        <div class="mb-2">
            <img 
                class="bg-dark rounded-circle me-3" 
                style="width: 75px; height: 75px; float: left;" 
                src="{% static 'assets/staff/anthonyradcliffe.png' %}" />
            <div>
                <b>Anthony Radcliffe</b>
                <p>
                    <span class="text-primary">Head of Licensing</span><br>
                    Political Science BA
                </p>
            </div>
        </div>

        <div class="mb-2">
            <img 
                class="bg-dark rounded-circle me-3" 
                style="width: 75px; height: 75px; float: left;" 
                src="{% static 'assets/staff/jakesavitt.png' %}" 
                />
        </div>
    </div>

    {% comment %} <div class="row mb-3">
        <h2>Idealab</h2>
        <p>
            Idealab is a forum for new open-source project ideas. 
            If you would like to submit an idea, please fill out 
            the following form. Once the idea is approved it will 
            appear on the <a href="{% url 'idealab:index' %}">IdeaLab</a>
            webpage. Once ideas are approved and migrated, your idea will 
            officially be a project and will appear in the 
            <a href="{% url 'projects:index' %}">Projects</a> webpage.
        </p>
    </div>

    <div class="row mb-3">
        <h2>Projects</h2>
        <p>
            All Projects visible on the MakeOpenSource Github page are 
            open to contributions. Each project will have a contributions.txt 
            file to specify a contribution format unique to that project, to 
            ensure that submission adhere to existing formats.
        </p>
    </div> {% endcomment %}

    <div class="row">
        <h2>Get Involved</h2>
        <p>
            Current University at Buffalo Students can join the club through 
            our <a href="{% url 'join:index' %}">join portal</a>. For updates 
            on upcoming activities and events, join our Discord server. To check
             out our latest projects, take a look at our 
             <a href="https://github.com/makeopensource">GitHub</a> profile.
        </p>
    </div>

</div>
{% endblock %}